In [1]:
import numpy as np

In [2]:
def id(x):
    return x.__array_interface__['data'][0]

In [4]:
a = np.zeros(10); aid = id(a) ; aid

140555765879664

In [7]:
b = a.copy(); id(b) == aid

False

In [10]:
id(b)

140555765039040

In [13]:
a *= 2; id(a) == aid

True

In [14]:
c = a*2; id(c) == aid

False

In [17]:
%%timeit a = np.zeros(10000000)
a *= 2

100 loops, best of 3: 6.3 ms per loop


In [35]:
%%timeit a = np.zeros(10000000)
a = a*2

10 loops, best of 3: 35.9 ms per loop


In [39]:
a = np.zeros((10, 10)); aid = id(a)
b = a.reshape((1,-1)); id(b) == aid

True

In [45]:
print(a)
print(b)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [46]:
c = a.T.reshape((1, -1))

In [54]:
print(id(a) == id(c))
print(id(b) == id(c))

False
False


In [55]:
d = a.flatten(); id(d) == aid

False

In [56]:
e = a.ravel(); id(e) == aid

True

In [61]:
%timeit a.flatten()

The slowest run took 25.79 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 604 ns per loop


In [63]:
%timeit a.ravel()

The slowest run took 23.62 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 233 ns per loop


In [86]:
import numpy as np
y = np.array(((1,2,3), (4,5,6), (7,8,9)))

v = y.ravel()
c = y.flatten()

In [92]:
print(id(v) == id(y))

True


In [99]:
y[0] = (10,20,30)

print(y)
print(v)
print(c)

[[10 20 30]
 [ 4  5  6]
 [ 7  8  9]]
[10 20 30  4  5  6  7  8  9]
[1 2 3 4 5 6 7 8 9]


In [108]:
v[8] = 90
print(y)
print(v)
print(c)

[[10 20 30]
 [ 4  5  6]
 [ 7  8 90]]
[10 20 30  4  5  6  7  8 90]
[1 2 3 4 5 6 7 8 9]


In [112]:
n = 1000
a = np.arange(n)
ac = a[:, np.newaxis]
ar = a[np.newaxis, :]

In [115]:
%timeit np.tile(ac, (1,n)) * np.tile(ar, (n, 1))

100 loops, best of 3: 7.6 ms per loop


In [116]:
%timeit ar*ac

100 loops, best of 3: 2.39 ms per loop


In [117]:
a = np.array([0, 1, 2])

In [126]:
np.tile(a,(2,3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [128]:
n = 1000
a = np.arange(n)
ac = a[:, np.newaxis]
ar = a[np.newaxis, :]

In [138]:
np.tile(ac, (1,n)) * np.tile(ar, (n,1))

array([[     0,      0,      0, ...,      0,      0,      0],
       [     0,      1,      2, ...,    997,    998,    999],
       [     0,      2,      4, ...,   1994,   1996,   1998],
       ..., 
       [     0,    997,   1994, ..., 994009, 995006, 996003],
       [     0,    998,   1996, ..., 995006, 996004, 997002],
       [     0,    999,   1998, ..., 996003, 997002, 998001]])

In [174]:
ar * ac

array([[     0,      0,      0, ...,      0,      0,      0],
       [     0,      1,      2, ...,    997,    998,    999],
       [     0,      2,      4, ...,   1994,   1996,   1998],
       ..., 
       [     0,    997,   1994, ..., 994009, 995006, 996003],
       [     0,    998,   1996, ..., 995006, 996004, 997002],
       [     0,    999,   1998, ..., 996003, 997002, 998001]])

In [148]:
x = np.array((1,2,3))
y = np.array((4,5,6))

In [151]:
import numpy as np
data = np.array([1,2])
data[:, np.newaxis] - data

array([[ 0, -1],
       [ 1,  0]])

In [177]:
dataac = data[:, np.newaxis]
dataar = data[np.newaxis, :]

In [194]:
data1 = np.array([[1,2]])
data2 = np.array([[1], [2]])

In [198]:
data1 

array([[1, 2]])

In [263]:
import numpy as np
a1 = np.array([[1,2,3,4,5,6,7,8]])
a1.reshape(2,1,4)

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [1]:
import numpy as np
a = np.random.rand(5000, 5000)